name: niffler

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  BASE_URL: http://frontend.niffler.dc
  AUTH_URL: http://auth.niffler.dc:9000
  API_URL: http://gateway.niffler.dc:8090
  SPEND_DB_URL: postgresql+psycopg2://postgres:secret@localhost:5432/niffler-spend
  USER_DB_URL: postgresql+psycopg2://postgres:secret@localhost:5432/niffler-auth
  USERDATA_DB_URL: postgresql+psycopg2://postgres:secret@localhost:5432/niffler-userdata
  KAFKA: localhost:9093
  SOAP: http://localhost:8089/ws
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backends
        run: |
          bash docker-compose-dev.sh

      - name: Run CurrencyMock gRPC container
        run: |
          bash docker-compose-mock.sh
#        run: |
#          docker run -d \
#          --name currencymock.niffler.dc \
#          -p 8888:8888 \
#          -p 8094:8094 \
#          -v ${{ github.workspace }}/wiremock/grpc:/wiremock \
#          -v ${{ github.workspace }}/tests/grpc/protos:/proto \
#          -e GRPC_SERVER_PORT=8094 \
#          adven27/grpc-wiremock:latest

      - name: Edit hosts file
        run: |
          echo -e "127.0.0.1\tlocalhost\n127.0.0.1\tfrontend.niffler.dc\n127.0.0.1\tauth.niffler.dc\n127.0.0.1\tgateway.niffler.dc\n127.0.0.1\tkafka\n127.0.0.1\tcurrencymock.niffler.dc" | sudo tee -a /etc/hosts
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Dependencies
        run: |
          pip install -r tests/requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install --with-deps

      - name: Run tests without grpc wiremock tests
        if: always()
        run: pytest -k "not wiremock"
        continue-on-error: true

      - name: Run tests only grpc wiremock tests
        if: always()
        run: pytest -k "wiremock" --mock
        continue-on-error: true

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results


  report:
    name: Generate Allure Report
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: allure-preview
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
